"""runs/ 命名规范化（自适应命名）：``pipeline/run_paths.py`` 助手 + ``tools/test.py`` 评测命名路径。

覆盖（用户定稿契约）：

① ``canonical_run_name``：规范名透传（秒/分戳）/ 伪前缀（``BTC<YYYYMMDD>-``）纠正 /
   缺省（None）生成 / 幂等；
② ``tools/test.py``：``--name`` 缺省 → ``BTC<秒级北京戳>_eval500_<policy>``；非规范名被规范化
   （``EXP_foo`` → ``BTC<戳>_EXP_foo``）；规范名原样；``--out`` 是路径根（显式 ``/tmp/...``
   或含 ``/`` 的路径不得当名字处理）。

纯离线：桩掉 ``eval_runner`` 与 GL 预载，不建 env。
"""

from __future__ import annotations

import re
from datetime import datetime, timedelta, timezone
from pathlib import Path

from pipeline import run_paths

ROOT = Path(__file__).resolve().parents[1]
STAMP = r"\d{8}-\d{6}"  # 秒级北京戳


# ------------------------------------------------ ① run_paths 助手（幂等规范化）
def test_beijing_stamp_seconds_format() -> None:
    frozen = datetime(2026, 1, 2, 3, 4, 5, tzinfo=timezone(timedelta(hours=8)))
    assert run_paths.beijing_stamp_seconds(frozen) == "20260102-030405"
    assert re.fullmatch(STAMP, run_paths.beijing_stamp_seconds())
    assert run_paths.beijing_stamp_seconds() != run_paths.beijing_stamp(), "秒级戳比分钟戳长"


def test_canonical_run_name_passthrough() -> None:
    """已是规范前缀（秒/分戳）→ 原样返回（幂等第一半）。"""
    for name in (
        "BTC20260929-164309_stageB_phase3_r5",
        "BTC20260929-1643_eval500_baseline",
        "BTC20260929-164309",
    ):
        assert run_paths.canonical_run_name(name, stamp="20260101-000000") == name


def test_canonical_run_name_fixes_pseudo_prefix_and_is_idempotent() -> None:
    """伪前缀（只有日期段的手拼漂移）→ 剥掉后补新秒级戳；再次规范化（换戳）不变。"""
    fixed = run_paths.canonical_run_name("BTC20260929-EXP_repro_r5", stamp="20260101-000000")
    assert fixed == "BTC20260101-000000_EXP_repro_r5"
    assert run_paths.canonical_run_name(fixed, stamp="20261231-235959") == fixed, "幂等"
    # 裸名（无任何 BTC 前缀）同样补戳
    assert run_paths.canonical_run_name("EXP_foo", stamp="20260101-000000") == "BTC20260101-000000_EXP_foo"


def test_canonical_run_name_generates_when_missing() -> None:
    """None → 直接用 kind/tag 生成；stamp 原样透传（phase3 的 TEST 戳兼容）。"""
    assert run_paths.canonical_run_name(kind="eval500", tag="phase3_r3", stamp="20260101-000000") == (
        "BTC20260101-000000_eval500_phase3_r3"
    )
    assert run_paths.canonical_run_name(kind="stageB", tag="phase3_r1", stamp="20260101-000000") == (
        "BTC20260101-000000_stageB_phase3_r1"
    )
    assert run_paths.canonical_run_name(stamp="20260101-000000") == "BTC20260101-000000"
    assert run_paths.canonical_run_name(kind="phase3_loop", stamp="TEST") == "BTCTEST_phase3_loop"


def test_eval_run_name_kind_and_path_guard() -> None:
    assert run_paths.spec_run_kind("env/specs/scenarios_eval500.json") == "eval500"
    assert run_paths.spec_run_kind("env/specs/scenarios_val.json") == "val"
    assert run_paths.spec_run_kind(None, default="eval500") == "eval500"
    # 缺省 → BTC<戳>_<spec kind>_<policy>
    assert run_paths.eval_run_name(
        None, spec="env/specs/scenarios_eval500.json", policy="ckpt", stamp="20260101-000000"
    ) == "BTC20260101-000000_eval500_ckpt"
    # 非规范名 → 纠正（不带 kind/policy；用户显式给的名字优先）
    assert run_paths.eval_run_name(
        "EXP_foo", spec="env/specs/scenarios_eval500.json", policy="ckpt", stamp="20260101-000000"
    ) == "BTC20260101-000000_EXP_foo"
    # 路径型 name 原样（与 --out 同口径：显式路径不当名字处理）
    assert run_paths.eval_run_name("/tmp/eval_x", spec="env/specs/scenarios_eval500.json") == "/tmp/eval_x"
    assert run_paths.eval_run_name("nested/dir", policy="baseline") == "nested/dir"


# ------------------------------------------------ ② tools/test.py 评测命名路径
def _drive_test_entry(monkeypatch, tmp_path: Path, *extra: str) -> "list[str]":
    """驱动 ``tools/test.py.main``：桩掉 eval_runner 与 GL 预载，返回转发给 eval_runner 的 argv。"""
    import tools.test as test_entry

    captured: dict = {}

    def _fake_eval_main(argv):
        captured["argv"] = [str(item) for item in argv]
        return 0

    monkeypatch.setattr("pipeline.eval_runner.main", _fake_eval_main)
    monkeypatch.setattr("pipeline.gl_runtime.ensure_gl_library_path", lambda **kwargs: None)
    rc = test_entry.main([
        "--config", str(ROOT / "config/default.yaml"),
        "--policy", "baseline",
        "--out", str(tmp_path),
        *extra,
    ])
    assert rc == 0, "tools/test.py 应走完（eval_runner 已桩掉）"
    assert "argv" in captured
    return captured["argv"]


def _name_of(argv: "list[str]") -> str:
    assert argv.count("--name") == 1, "转发 argv 必须只有一个 --name（raw 值须被去重）"
    return argv[argv.index("--name") + 1]


def test_test_entry_default_name_autogenerated_out_is_root(tmp_path: Path, monkeypatch) -> None:
    argv = _drive_test_entry(monkeypatch, tmp_path)
    name = _name_of(argv)
    assert re.fullmatch(rf"BTC{STAMP}_eval500_baseline", name), name
    assert argv[argv.index("--out") + 1] == str(tmp_path), "--out 是路径根：不得被当名字规范化"
    assert (tmp_path / name / "manifest.txt").is_file(), "布局/取证必须落 <out>/<name>/"


def test_test_entry_normalizes_non_canonical_name(tmp_path: Path, monkeypatch) -> None:
    argv = _drive_test_entry(monkeypatch, tmp_path, "--name", "EXP_foo")
    name = _name_of(argv)
    assert re.fullmatch(rf"BTC{STAMP}_EXP_foo", name), name
    assert (tmp_path / name / "manifest.txt").is_file()


def test_test_entry_passthrough_canonical_and_path_names(tmp_path: Path, monkeypatch) -> None:
    argv = _drive_test_entry(monkeypatch, tmp_path, "--name", "BTC20260101-120000_exp_r5")
    assert _name_of(argv) == "BTC20260101-120000_exp_r5", "规范名必须透传"

    explicit = tmp_path / "explicit_dir"
    argv2 = _drive_test_entry(monkeypatch, tmp_path, "--name", str(explicit))
    assert _name_of(argv2) == str(explicit), "显式路径型 --name 不得当名字处理"
    assert (explicit / "manifest.txt").is_file()
